/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNodeDialog: typeof import('./components/dialogs/AddNodeDialog.vue')['default']
    AlignGuide: typeof import('./components/AlignGuide.vue')['default']
    CodeNode: typeof import('./components/nodes/CodeNode.vue')['default']
    ConnLineEdge: typeof import('./components/ConnLineEdge.vue')['default']
    CustomEdge: typeof import('./components/CustomEdge.vue')['default']
    EndNode: typeof import('./components/nodes/EndNode.vue')['default']
    FlowTools: typeof import('./components/FlowTools.vue')['default']
    LLMNode: typeof import('./components/nodes/LLMNode.vue')['default']
    MarkdownEditor: typeof import('./components/MarkdownEditor.vue')['default']
    NodeInfoDialog: typeof import('./components/dialogs/NodeInfoDialog.vue')['default']
    OutNode: typeof import('./components/nodes/OutNode.vue')['default']
    PendingNode: typeof import('./components/nodes/PendingNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialEdge: typeof import('./components/SpecialEdge.vue')['default']
    StartNode: typeof import('./components/nodes/StartNode.vue')['default']
    TextEditable: typeof import('./components/TextEditable.vue')['default']
    TextTooltip: typeof import('./components/TextTooltip.vue')['default']
    TextTooltip2: typeof import('./components/TextTooltip2.vue')['default']
    TextTooltipOld: typeof import('./components/TextTooltipOld.vue')['default']
    ToolNode: typeof import('./components/nodes/ToolNode.vue')['default']
  }
}
